server:
  port: 18080

spring:
  application:
    name: distributed-cache
  data:
    redis:
      host: localhost
      port: 6379
      # For production: use password, TLS, cluster/sentinel
      timeout: 2000
      client-type: lettuce
      lettuce:
        shutdown-timeout: 100
        pool:
          enabled: true
          max-active: 64
          max-idle: 16
          min-idle: 4
  datasource:
    url: jdbc:postgresql://localhost:15432/cachedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.example.cache: DEBUG
    org.springframework.cache: DEBUG